/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.4.1 on 2012-11-28 11:15:49,
 any modifications will be overwritten.
 ==============================================================
 */

package temp;

/**
 * The root element of Nexus LVO Plugin configuration.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class BeanConfig
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * The version of the persisted model.
     */
    private String version;

    /**
     * Field lvoKeys.
     */
    private java.util.List<BeanKey> lvoKeys;

    /**
     * Enable the LVO check.
     */
    private boolean enabled = true;

    /**
     * Field modelEncoding.
     */
    private String modelEncoding = "UTF-8";


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addLvoKey.
     * 
     * @param cLvoKey
     */
    public void addLvoKey( BeanKey cLvoKey )
    {
        getBeanKeys().add( cLvoKey );
    } //-- void addLvoKey( CLvoKey )

    /**
     * Method getLvoKeys.
     * 
     * @return List
     */
    public java.util.List<BeanKey> getBeanKeys()
    {
        if ( this.lvoKeys == null )
        {
            this.lvoKeys = new java.util.ArrayList<BeanKey>();
        }

        return this.lvoKeys;
    } //-- java.util.List<CLvoKey> getLvoKeys()

    /**
     * Get the modelEncoding field.
     * 
     * @return String
     */
    public String getModelEncoding()
    {
        return this.modelEncoding;
    } //-- String getModelEncoding()

    /**
     * Get the version of the persisted model.
     * 
     * @return String
     */
    public String getVersion()
    {
        return this.version;
    } //-- String getVersion()

    /**
     * Get enable the LVO check.
     * 
     * @return boolean
     */
    public boolean isEnabled()
    {
        return this.enabled;
    } //-- boolean isEnabled()

    /**
     * Method removeLvoKey.
     * 
     * @param cLvoKey
     */
    public void removeLvoKey( BeanKey cLvoKey )
    {
        getBeanKeys().remove( cLvoKey );
    } //-- void removeLvoKey( CLvoKey )

    /**
     * Set enable the LVO check.
     * 
     * @param enabled
     */
    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    } //-- void setEnabled( boolean )

    /**
     * Set a list of LVO keys.
     * 
     * @param lvoKeys
     */
    public void setLvoKeys( java.util.List<BeanKey> lvoKeys )
    {
        this.lvoKeys = lvoKeys;
    } //-- void setLvoKeys( java.util.List )

    /**
     * Set the modelEncoding field.
     * 
     * @param modelEncoding
     */
    public void setModelEncoding( String modelEncoding )
    {
        this.modelEncoding = modelEncoding;
    } //-- void setModelEncoding( String )

    /**
     * Set the version of the persisted model.
     * 
     * @param version
     */
    public void setVersion( String version )
    {
        this.version = version;
    } //-- void setVersion( String )

    
    public static final String MODEL_VERSION = "1.0.1";

}
