/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.4.1 on 2012-11-28 11:15:49,
 any modifications will be overwritten.
 ==============================================================
 */

package temp;

/**
 * An key that is published for LVO query.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class BeanKey
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * The repository id.
     */
    private String key;

    /**
     * The repository id.
     */
    private String strategy;

    /**
     * The repository id.
     */
    private String groupId;

    /**
     * The repository id.
     */
    private String artifactId;

    /**
     * The repository id.
     */
    private String repositoryId;

    /**
     * The URL of remote target.
     */
    private String remoteUrl;

    /**
     * The path of local content target.
     */
    private String localPath;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the repository id.
     * 
     * @return String
     */
    public String getArtifactId()
    {
        return this.artifactId;
    } //-- String getArtifactId()

    /**
     * Get the repository id.
     * 
     * @return String
     */
    public String getGroupId()
    {
        return this.groupId;
    } //-- String getGroupId()

    /**
     * Get the repository id.
     * 
     * @return String
     */
    public String getKey()
    {
        return this.key;
    } //-- String getKey()

    /**
     * Get the path of local content target.
     * 
     * @return String
     */
    public String getLocalPath()
    {
        return this.localPath;
    } //-- String getLocalPath()

    /**
     * Get the URL of remote target.
     * 
     * @return String
     */
    public String getRemoteUrl()
    {
        return this.remoteUrl;
    } //-- String getRemoteUrl()

    /**
     * Get the repository id.
     * 
     * @return String
     */
    public String getRepositoryId()
    {
        return this.repositoryId;
    } //-- String getRepositoryId()

    /**
     * Get the repository id.
     * 
     * @return String
     */
    public String getStrategy()
    {
        return this.strategy;
    } //-- String getStrategy()

    /**
     * Set the repository id.
     * 
     * @param artifactId
     */
    public void setArtifactId( String artifactId )
    {
        this.artifactId = artifactId;
    } //-- void setArtifactId( String )

    /**
     * Set the repository id.
     * 
     * @param groupId
     */
    public void setGroupId( String groupId )
    {
        this.groupId = groupId;
    } //-- void setGroupId( String )

    /**
     * Set the repository id.
     * 
     * @param key
     */
    public void setKey( String key )
    {
        this.key = key;
    } //-- void setKey( String )

    /**
     * Set the path of local content target.
     * 
     * @param localPath
     */
    public void setLocalPath( String localPath )
    {
        this.localPath = localPath;
    } //-- void setLocalPath( String )

    /**
     * Set the URL of remote target.
     * 
     * @param remoteUrl
     */
    public void setRemoteUrl( String remoteUrl )
    {
        this.remoteUrl = remoteUrl;
    } //-- void setRemoteUrl( String )

    /**
     * Set the repository id.
     * 
     * @param repositoryId
     */
    public void setRepositoryId( String repositoryId )
    {
        this.repositoryId = repositoryId;
    } //-- void setRepositoryId( String )

    /**
     * Set the repository id.
     * 
     * @param strategy
     */
    public void setStrategy( String strategy )
    {
        this.strategy = strategy;
    } //-- void setStrategy( String )

}
